package com.eimsound.rest.test.infra

import com.eimsound.rest.test.entity.Author
import com.eimsound.rest.test.entity.Book
import com.eimsound.rest.test.entity.BookStore
import com.eimsound.rest.test.entity.Gender
import com.eimsound.rest.test.entity.OrderItem
import org.babyfish.jimmer.sql.ast.mutation.AssociatedSaveMode
import org.babyfish.jimmer.sql.ast.mutation.SaveMode
import org.babyfish.jimmer.sql.dialect.H2Dialect
import org.babyfish.jimmer.sql.kt.KSqlClient
import org.babyfish.jimmer.sql.kt.newKSqlClient
import org.babyfish.jimmer.sql.runtime.ConnectionManager
import org.babyfish.jimmer.sql.runtime.Executor
import org.h2.jdbcx.JdbcDataSource
import java.math.BigDecimal
import javax.sql.DataSource

object TestEnv {

    val dataSource: DataSource = JdbcDataSource().apply {
        setURL("jdbc:h2:mem:ktor_jimmer_rest_test;DB_CLOSE_DELAY=-1")
        user = "sa"
        password = ""
    }

    val sqlClient: KSqlClient by lazy {
        initSchema()
        newKSqlClient {
            setDialect(H2Dialect())
            setConnectionManager(ConnectionManager.simpleConnectionManager(dataSource))
            setExecutor(Executor.log())
        }
    }

    fun cleanDatabase() {
        sqlClient
        dataSource.connection.use { connection ->
            connection.createStatement().use { statement ->
                statement.execute("DELETE FROM book_author_mapping")
                statement.execute("DELETE FROM book")
                statement.execute("DELETE FROM author")
                statement.execute("DELETE FROM order_item")
                statement.execute("DELETE FROM book_store")
            }
        }
    }

    fun saveBookStore(name: String, website: String? = null): BookStore =
        sqlClient.save(
            BookStore {
                this.name = name
                this.website = website
            },
            SaveMode.INSERT_ONLY,
            AssociatedSaveMode.MERGE
        ).modifiedEntity

    fun saveAuthor(
        firstName: String,
        lastName: String,
        gender: Gender = Gender.MALE,
    ): Author = sqlClient.save(
        Author {
            this.firstName = firstName
            this.lastName = lastName
            this.gender = gender
        },
        SaveMode.INSERT_ONLY,
        AssociatedSaveMode.MERGE
    ).modifiedEntity

    fun saveBook(
        name: String,
        edition: Int = 1,
        price: BigDecimal = BigDecimal("50"),
        store: BookStore? = null,
    ): Book = sqlClient.save(
        Book {
            this.name = name
            this.edition = edition
            this.price = price
            if (store != null) {
                this.store = store
            }
        },
        SaveMode.INSERT_ONLY,
        AssociatedSaveMode.MERGE
    ).modifiedEntity

    fun saveOrderItem(code: String, store: BookStore? = null): OrderItem =
        sqlClient.save(
            OrderItem {
                this.code = code
                if (store != null) {
                    this.store = store
                }
            },
            SaveMode.INSERT_ONLY,
            AssociatedSaveMode.MERGE
        ).modifiedEntity

    private fun initSchema() {
        dataSource.connection.use { connection ->
            connection.createStatement().use { statement ->
                SCHEMA_SQL.split(";").map { it.trim() }.filter { it.isNotEmpty() }.forEach { sql ->
                    statement.execute(sql)
                }
            }
        }
    }

    private val SCHEMA_SQL = """
        CREATE TABLE IF NOT EXISTS book_store (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            website VARCHAR(100)
        );
        ALTER TABLE book_store ADD CONSTRAINT IF NOT EXISTS business_key_book_store UNIQUE (name);

        CREATE TABLE IF NOT EXISTS book (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            edition INTEGER NOT NULL,
            price NUMERIC(10, 2) NOT NULL,
            store_id BIGINT
        );
        ALTER TABLE book ADD CONSTRAINT IF NOT EXISTS business_key_book UNIQUE (name, edition);
        ALTER TABLE book ADD CONSTRAINT IF NOT EXISTS fk_book__book_store
            FOREIGN KEY (store_id) REFERENCES book_store (id);

        CREATE TABLE IF NOT EXISTS author (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            first_name VARCHAR(100) NOT NULL,
            last_name VARCHAR(100) NOT NULL,
            gender VARCHAR(1) NOT NULL
        );
        ALTER TABLE author ADD CONSTRAINT IF NOT EXISTS business_key_author UNIQUE (first_name, last_name);

        CREATE TABLE IF NOT EXISTS book_author_mapping (
            book_id BIGINT NOT NULL,
            author_id BIGINT NOT NULL,
            PRIMARY KEY (book_id, author_id)
        );
        ALTER TABLE book_author_mapping ADD CONSTRAINT IF NOT EXISTS fk_book_author_mapping__book
            FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE;
        ALTER TABLE book_author_mapping ADD CONSTRAINT IF NOT EXISTS fk_book_author_mapping__author
            FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE;

        CREATE TABLE IF NOT EXISTS order_item (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code VARCHAR(100) NOT NULL,
            store_id BIGINT,
            store_name VARCHAR(100)
        );
        ALTER TABLE order_item ADD CONSTRAINT IF NOT EXISTS business_key_order_item UNIQUE (code);
        ALTER TABLE order_item ADD CONSTRAINT IF NOT EXISTS fk_order_item__book_store
            FOREIGN KEY (store_id) REFERENCES book_store (id);
    """.trimIndent()
}
